server.port=8080
spring.application.name=spring_boot

# ==========================
# DataSource
# ==========================

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/orcl1
spring.datasource.username=C##IGFI
spring.datasource.password=P@ssw0rd

# ==========================
# JPA / Hibernate
# ==========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
