server.port=8086
spring.application.name=Spring-Tasklec11

# ==========================
# DataSource
# ==========================
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/orcl1
spring.datasource.username=C##UNIVERSITY
spring.datasource.password=P@ssw0rd

# ==========================
# JPA / Hibernate
# ==========================
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true